# Dependabot will run on day 23 of each month at 03:52 (Europe/Berlin timezone)
version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "52 3 23 * *"
    open-pull-requests-limit: 20
    assignees:
      - "foxthefox"
    versioning-strategy: "increase"
